In [1]:
import pandas as pd
import numpy as np

In [2]:

import streamlit as st

In [3]:
pip install streamlit

Note: you may need to restart the kernel to use updated packages.


In [4]:
df1 = pd.read_csv('adult.csv')

In [5]:
df1_col=['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country','target']

In [6]:
df1

age          workclass  fnlwgt    education  education-num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gain  capital-loss  hours-per-week  native-country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       target  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [7]:
len(df1_col)

15

In [8]:
df1.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'target'],
      dtype='object')

In [9]:
# asd={}
# for i in df.columns:
#     asd[i]=df_col[i]

In [10]:
# df=df.rename(columns=asd)

In [11]:
df1.to_csv('adult.csv',index=False)

In [12]:
df1=pd.read_csv('adult.csv')

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [14]:
df1

age          workclass  fnlwgt    education  education-num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gain  capital-loss  hours-per-week  native-country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       target  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [15]:
df1.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
target            object
dtype: object

In [16]:
# Only plot numeric columns to avoid layout errors
numeric_cols = df1.select_dtypes(include='number').columns
df1[numeric_cols].plot(kind='box', subplots=True, layout=(2, 3), figsize=(12, 8))
plt.show()

C:\Users\jojot\AppData\Local\Temp\ipykernel_9484\868622146.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


In [17]:
df1.hist()
plt.show()

C:\Users\jojot\AppData\Local\Temp\ipykernel_9484\1122961062.py:2: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


In [18]:
target_numeric = df1['target'].apply(lambda x: 1 if '>50K' in x else 0)
print(df1['fnlwgt'].corr(target_numeric))


-0.009462557247529197


Drop fnlwgt because the correlation coefficient between fnlwgt and target is -0.009462557247529197 which is close to 0 meaning that there is essentially no relation between fnlwgt and target therefore irrelavant. 

The education-num column duplicates information already captured by the numeric education-num feature. Keeping both causes redundancy and complicates preprocessing. 


In [19]:
df1 = df1.drop(columns=['fnlwgt', 'education-num'])

In [20]:
df1

age          workclass    education       marital-status  \
0       39          State-gov    Bachelors        Never-married   
1       50   Self-emp-not-inc    Bachelors   Married-civ-spouse   
2       38            Private      HS-grad             Divorced   
3       53            Private         11th   Married-civ-spouse   
4       28            Private    Bachelors   Married-civ-spouse   
...    ...                ...          ...                  ...   
32556   27            Private   Assoc-acdm   Married-civ-spouse   
32557   40            Private      HS-grad   Married-civ-spouse   
32558   58            Private      HS-grad              Widowed   
32559   22            Private      HS-grad        Never-married   
32560   52       Self-emp-inc      HS-grad   Married-civ-spouse   

               occupation    relationship    race      sex  capital-gain  \
0            Adm-clerical   Not-in-family   White     Male          2174   
1         Exec-managerial         Husband   White     Male             0   
2       Handlers-cleaners   Not-in-family   White     Male             0   
3       Handlers-cleaners         Husband   Black     Male             0   
4          Prof-specialty            Wife   Black   Female             0   
...                   ...             ...     ...      ...           ...   
32556        Tech-support            Wife   White   Female             0   
32557   Machine-op-inspct         Husband   White     Male             0   
32558        Adm-clerical       Unmarried   White   Female             0   
32559        Adm-clerical       Own-child   White     Male             0   
32560     Exec-managerial            Wife   White   Female         15024   

       capital-loss  hours-per-week  native-country  target  
0                 0              40   United-States   <=50K  
1                 0              13   United-States   <=50K  
2                 0              40   United-States   <=50K  
3                 0              40   United-States   <=50K  
4                 0              40            Cuba   <=50K  
...             ...             ...             ...     ...  
32556             0              38   United-States   <=50K  
32557             0              40   United-States    >50K  
32558             0              40   United-States   <=50K  
32559             0              20   United-States   <=50K  
32560             0              40   United-States    >50K  

[32561 rows x 13 columns]

In [21]:
df1_col

['age',
 'workclass',
 'fnlwgt',
 'education',
 'education-num',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'capital-gain',
 'capital-loss',
 'hours-per-week',
 'native-country',
 'target']

Perform OHE on non integer variables

In [22]:
df1=pd.get_dummies(df1,columns=['workclass', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country', 'education'], drop_first=True)

In [23]:
df1.columns

Index(['age', 'capital-gain', 'capital-loss', 'hours-per-week', 'target',
       'workclass_ Federal-gov', 'workclass_ Local-gov',
       'workclass_ Never-worked', 'workclass_ Private',
       'workclass_ Self-emp-inc', 'workclass_ Self-emp-not-inc',
       'workclass_ State-gov', 'workclass_ Without-pay',
       'marital-status_ Married-AF-spouse',
       'marital-status_ Married-civ-spouse',
       'marital-status_ Married-spouse-absent',
       'marital-status_ Never-married', 'marital-status_ Separated',
       'marital-status_ Widowed', 'occupation_ Adm-clerical',
       'occupation_ Armed-Forces', 'occupation_ Craft-repair',
       'occupation_ Exec-managerial', 'occupation_ Farming-fishing',
       'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct',
       'occupation_ Other-service', 'occupation_ Priv-house-serv',
       'occupation_ Prof-specialty', 'occupation_ Protective-serv',
       'occupation_ Sales', 'occupation_ Tech-support',
       'occupation_ Transpo

In [24]:
cols_to_remove = [col for col in df1.columns if col in ['workclass_ ?', 'occupation_ ?', 'native-country_ ?']]
df1 = df1.drop(columns=cols_to_remove)

In [25]:
df1.dtypes

age                         int64
capital-gain                int64
capital-loss                int64
hours-per-week              int64
target                     object
                            ...  
education_ HS-grad           bool
education_ Masters           bool
education_ Preschool         bool
education_ Prof-school       bool
education_ Some-college      bool
Length: 99, dtype: object

In [26]:
df1.filter(like='workclass').head()

workclass_ Federal-gov  workclass_ Local-gov  workclass_ Never-worked  \
0                   False                 False                    False   
1                   False                 False                    False   
2                   False                 False                    False   
3                   False                 False                    False   
4                   False                 False                    False   

   workclass_ Private  workclass_ Self-emp-inc  workclass_ Self-emp-not-inc  \
0               False                    False                        False   
1               False                    False                         True   
2                True                    False                        False   
3                True                    False                        False   
4                True                    False                        False   

   workclass_ State-gov  workclass_ Without-pay  
0                  True                   False  
1                 False                   False  
2                 False                   False  
3                 False                   False  
4                 False                   False

In [27]:
df1.head()

age  capital-gain  capital-loss  hours-per-week  target  \
0   39          2174             0              40   <=50K   
1   50             0             0              13   <=50K   
2   38             0             0              40   <=50K   
3   53             0             0              40   <=50K   
4   28             0             0              40   <=50K   

   workclass_ Federal-gov  workclass_ Local-gov  workclass_ Never-worked  \
0                   False                 False                    False   
1                   False                 False                    False   
2                   False                 False                    False   
3                   False                 False                    False   
4                   False                 False                    False   

   workclass_ Private  workclass_ Self-emp-inc  ...  education_ 9th  \
0               False                    False  ...           False   
1               False                    False  ...           False   
2                True                    False  ...           False   
3                True                    False  ...           False   
4                True                    False  ...           False   

   education_ Assoc-acdm  education_ Assoc-voc  education_ Bachelors  \
0                  False                 False                  True   
1                  False                 False                  True   
2                  False                 False                 False   
3                  False                 False                 False   
4                  False                 False                  True   

   education_ Doctorate  education_ HS-grad  education_ Masters  \
0                 False               False               False   
1                 False               False               False   
2                 False                True               False   
3                 False               False               False   
4                 False               False               False   

   education_ Preschool  education_ Prof-school  education_ Some-college  
0                 False                   False                    False  
1                 False                   False                    False  
2                 False                   False                    False  
3                 False                   False                    False  
4                 False                   False                    False  

[5 rows x 99 columns]

In [28]:
df1 = df1[~df1.apply(lambda row: row.astype(str).str.contains('\?').any(), axis=1)]

<>:1: SyntaxWarning: invalid escape sequence '\?'
<>:1: SyntaxWarning: invalid escape sequence '\?'
C:\Users\jojot\AppData\Local\Temp\ipykernel_9484\521118534.py:1: SyntaxWarning: invalid escape sequence '\?'
  df1 = df1[~df1.apply(lambda row: row.astype(str).str.contains('\?').any(), axis=1)]


Without combining government types

In [29]:
df1

age  capital-gain  capital-loss  hours-per-week  target  \
0       39          2174             0              40   <=50K   
1       50             0             0              13   <=50K   
2       38             0             0              40   <=50K   
3       53             0             0              40   <=50K   
4       28             0             0              40   <=50K   
...    ...           ...           ...             ...     ...   
32556   27             0             0              38   <=50K   
32557   40             0             0              40    >50K   
32558   58             0             0              40   <=50K   
32559   22             0             0              20   <=50K   
32560   52         15024             0              40    >50K   

       workclass_ Federal-gov  workclass_ Local-gov  workclass_ Never-worked  \
0                       False                 False                    False   
1                       False                 False                    False   
2                       False                 False                    False   
3                       False                 False                    False   
4                       False                 False                    False   
...                       ...                   ...                      ...   
32556                   False                 False                    False   
32557                   False                 False                    False   
32558                   False                 False                    False   
32559                   False                 False                    False   
32560                   False                 False                    False   

       workclass_ Private  workclass_ Self-emp-inc  ...  education_ 9th  \
0                   False                    False  ...           False   
1                   False                    False  ...           False   
2                    True                    False  ...           False   
3                    True                    False  ...           False   
4                    True                    False  ...           False   
...                   ...                      ...  ...             ...   
32556                True                    False  ...           False   
32557                True                    False  ...           False   
32558                True                    False  ...           False   
32559                True                    False  ...           False   
32560               False                     True  ...           False   

       education_ Assoc-acdm  education_ Assoc-voc  education_ Bachelors  \
0                      False                 False                  True   
1                      False                 False                  True   
2                      False                 False                 False   
3                      False                 False                 False   
4                      False                 False                  True   
...                      ...                   ...                   ...   
32556                   True                 False                 False   
32557                  False                 False                 False   
32558                  False                 False                 False   
32559                  False                 False                 False   
32560                  False                 False                 False   

       education_ Doctorate  education_ HS-grad  education_ Masters  \
0                     False               False               False   
1                     False               False               False   
2                     False                True               False   
3                     False               False               False   
4                     False               False               False   
...          

Non combining local-gov, federal-gov and state-gov

In [30]:
X= df1.drop('target', axis = 1).to_numpy()

In [31]:
y=df1[['target']].to_numpy()

In [32]:
%pip install --upgrade scikit-learn numpy


Note: you may need to restart the kernel to use updated packages.


In [33]:
# %pip install --upgrade numpy

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

logr = LogisticRegression(max_iter= 200)
lda = LinearDiscriminantAnalysis()
knn = KNeighborsClassifier()
svm = SVC()

In [35]:
logr.fit(X_train, y_train)
lda.fit(X_train, y_train)
knn.fit(X_train, y_train)
svm.fit(X_train, y_train)

C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 200 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=200).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversi

SVC()

In [36]:
y_pred = svm.predict(X_test)

In [37]:
from sklearn.metrics import accuracy_score
accuracy_score (y_test, y_pred)

0.8023952095808383

In [38]:
print ("Logistic : ", accuracy_score(y_test, logr.predict(X_test)))
print ("LDA: ", accuracy_score(y_test, lda.predict(X_test)))
print ("KNN: ", accuracy_score(y_test, knn.predict(X_test)))
print ("SVM: ", accuracy_score(y_test, svm.predict(X_test)))

Logistic :  0.8426224474128666
LDA:  0.8352525717795178
KNN:  0.8409335175802242
SVM:  0.8023952095808383


In [39]:
# X = df.drop('target', axis=1).to_numpy()
# y = df['target'].to_numpy()
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=8)
# # y = (pd.Series(y).str.strip() == '>50K').astype(int)

In [40]:
y

array([[' <=50K'],
       [' <=50K'],
       [' <=50K'],
       ...,
       [' <=50K'],
       [' <=50K'],
       [' >50K']], shape=(32561, 1), dtype=object)

In [41]:
df1.columns

Index(['age', 'capital-gain', 'capital-loss', 'hours-per-week', 'target',
       'workclass_ Federal-gov', 'workclass_ Local-gov',
       'workclass_ Never-worked', 'workclass_ Private',
       'workclass_ Self-emp-inc', 'workclass_ Self-emp-not-inc',
       'workclass_ State-gov', 'workclass_ Without-pay',
       'marital-status_ Married-AF-spouse',
       'marital-status_ Married-civ-spouse',
       'marital-status_ Married-spouse-absent',
       'marital-status_ Never-married', 'marital-status_ Separated',
       'marital-status_ Widowed', 'occupation_ Adm-clerical',
       'occupation_ Armed-Forces', 'occupation_ Craft-repair',
       'occupation_ Exec-managerial', 'occupation_ Farming-fishing',
       'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct',
       'occupation_ Other-service', 'occupation_ Priv-house-serv',
       'occupation_ Prof-specialty', 'occupation_ Protective-serv',
       'occupation_ Sales', 'occupation_ Tech-support',
       'occupation_ Transpo

combined government (federal_gov, local_gov and state_gov)

In [42]:
# df_combinedgov['workclass']=df['workclass'].apply(lambda x: 'government' if 'gov' in x else x)

In [43]:
df = df1.copy()

In [44]:
df['workclass_government'] = (
    df.get('workclass_ Local-gov', False) |
    df.get('workclass_ State-gov', False) |
    df.get('workclass_ Federal-gov', False)
)
cols_to_drop = [col for col in ['workclass_ Local-gov', 'workclass_ State-gov', 'workclass_ Federal-gov'] if col in df.columns]
df = df.drop(columns=cols_to_drop)

In [45]:
df.columns

Index(['age', 'capital-gain', 'capital-loss', 'hours-per-week', 'target',
       'workclass_ Never-worked', 'workclass_ Private',
       'workclass_ Self-emp-inc', 'workclass_ Self-emp-not-inc',
       'workclass_ Without-pay', 'marital-status_ Married-AF-spouse',
       'marital-status_ Married-civ-spouse',
       'marital-status_ Married-spouse-absent',
       'marital-status_ Never-married', 'marital-status_ Separated',
       'marital-status_ Widowed', 'occupation_ Adm-clerical',
       'occupation_ Armed-Forces', 'occupation_ Craft-repair',
       'occupation_ Exec-managerial', 'occupation_ Farming-fishing',
       'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct',
       'occupation_ Other-service', 'occupation_ Priv-house-serv',
       'occupation_ Prof-specialty', 'occupation_ Protective-serv',
       'occupation_ Sales', 'occupation_ Tech-support',
       'occupation_ Transport-moving', 'relationship_ Not-in-family',
       'relationship_ Other-relative', 'relat

In [46]:
df.dtypes

age                         int64
capital-gain                int64
capital-loss                int64
hours-per-week              int64
target                     object
                            ...  
education_ Masters           bool
education_ Preschool         bool
education_ Prof-school       bool
education_ Some-college      bool
workclass_government         bool
Length: 97, dtype: object

In [47]:
X_combined= df.drop('target', axis = 1).to_numpy()

In [48]:
y_combined=df[['target']].to_numpy()

In [49]:
from sklearn.model_selection import train_test_split
X_train_combined, X_test_combined, y_train_combined, y_test_combined = train_test_split(X_combined, y_combined, test_size=0.2, random_state=3)

In [50]:
logr.fit(X_train_combined, y_train_combined)
lda.fit(X_train_combined, y_train_combined)
knn.fit(X_train_combined, y_train_combined)
svm.fit(X_train_combined, y_train_combined)

C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 200 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=200).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversi

SVC()

In [51]:
y_pred_combined= svm.predict(X_test_combined)

In [52]:
from sklearn.metrics import accuracy_score
accuracy_score (y_test_combined, y_pred_combined)

0.8023952095808383

In [53]:
print ("Logistic : ", accuracy_score(y_test_combined, logr.predict(X_test_combined)))
print ("LDA: ", accuracy_score(y_test_combined, lda.predict(X_test_combined)))
print ("KNN: ", accuracy_score(y_test_combined, knn.predict(X_test_combined)))
print ("SVM: ", accuracy_score(y_test_combined, svm.predict(X_test_combined)))

Logistic :  0.8441578381698143
LDA:  0.836480884385076
KNN:  0.8400122831260556
SVM:  0.8023952095808383


### Model Evaluation Summary

#### Non-combined:
- Logistic :  0.8426224474128666
- LDA:  0.8352525717795178
- KNN:  0.8409335175802242
- SVM:  0.8023952095808383

#### Combined:
- Logistic :  0.8441578381698143
- LDA:  0.836480884385076
- KNN:  0.8400122831260556
- SVM:  0.8023952095808383

Individually,  State-gov, Federal-gov, and Local-gov have very few data points, which can make it hard for models to learn meaningful patterns. By merging  State-gov, Federal-gov, and Local-gov into one "Government" category, we gave the models more consistent data to train on.

After combining, the performance of Logistic Regression and LDA improved slightly, while SVM stayed the same and KNN performing very very slightly better. However in general, logistic regression still improved more

So overall, combining the government workclasses helped improve model performance or kept it stable which makes it a better choice for training.


In [54]:
import seaborn as sns

num_cols = ['age', 'capital-gain', 'capital-loss', 'hours-per-week']

plt.figure(figsize=(15,10))
for i, col in enumerate(num_cols, 1):
    plt.subplot(2, 3, i)
    sns.boxplot(data=df, x='target', y=col)
    plt.title(f'{col} by Income')
plt.tight_layout()
plt.show()

C:\Users\jojot\AppData\Local\Temp\ipykernel_9484\2391706665.py:11: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


conclusion for box plots above:
1. age by income
- People earning >50K tend to be older than those earning <=50K.
- Median age is higher in the >50K group
- There's some overlap, but this feature shows a clear upward trend with income.
- Age is positively correlated with income and may be a useful predictor.
2. Capital-Gain by Income
- For most people in both groups, capital gain is zero (very flat at the bottom).
- the >50K group has more outliers with high capital gains (e.g., 10,000 to 100,000).
- Capital gain is not common, but when it exists, it skews towards higher income.
- Capital gain has low variance overall, but high values are strongly associated with high income. Could be informative, especially for capturing outliers.Capital gain has low variance overall, but high values are strongly associated with high income. Could be informative, especially for capturing outliers.
3. Capital-Loss by income
- Similar to capital gain: most values are zero.
- The >50K group has slightly more instances with higher capital losses, but the difference is less dramatic than capital gain.
- Distribution is skewed with many zeros and a few high values.
- Capital loss may offer some predictive value, but it is less clear than capital gain.
4. Hours-per-week by Income
- People earning >50K tend to work more hours per week.
- Median and upper quartile are clearly higher for >50K group.
- Some outliers work extreme hours in both groups, but generally more hours = more income.
- Strong positive relationship between hours worked and income a very relevant feature.

In [55]:
import matplotlib.pyplot as plt
import pandas as pd

print("Data info:")
print(df['hours-per-week'].describe())

print("\nUnique values in target:")
print(df['target'].value_counts())

print("\nAny missing values?")
print(df[['hours-per-week', 'target']].isnull().sum())
income_counts = df['target'].value_counts()

plt.figure(figsize=(6, 6))
plt.pie(
    income_counts,
    labels=income_counts.index,
    autopct='%1.1f%%',
    startangle=140,
    colors=['skyblue', 'lightgreen']
)
plt.title('Income Group Distribution')
plt.axis('equal') 
plt.show()


Data info:
count    32561.000000
mean        40.437456
std         12.347429
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000
Name: hours-per-week, dtype: float64

Unique values in target:
target
<=50K    24720
>50K      7841
Name: count, dtype: int64

Any missing values?
hours-per-week    0
target            0
dtype: int64


C:\Users\jojot\AppData\Local\Temp\ipykernel_9484\1056802082.py:24: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


target values are not equal and therefore cannot use Accuracy

In [56]:
import seaborn as sns

import matplotlib.pyplot as plt

cols_to_plot = [col for col in df.columns if col != 'target']

plt.figure(figsize=(18, len(cols_to_plot) * 2.5))
for i, col in enumerate(cols_to_plot, 1):
    plt.subplot(len(cols_to_plot), 1, i)
    if df[col].dtype in ['int64', 'float64']:
        sns.boxplot(data=df, x='target', y=col)
        plt.title(f'{col} by Target')
    else:
        sns.countplot(data=df, x='target', hue=col)
        plt.title(f'{col} Distribution by Target')
    plt.tight_layout()
plt.show()

C:\Users\jojot\AppData\Local\Temp\ipykernel_9484\333268604.py:17: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


check if there is any empty columns

In [57]:
empty_cols = df.columns[df.isnull().all()]
print("Empty columns:", list(empty_cols))

empty_rows = df.index[df.isnull().all(axis=1)]
print("Empty rows:", list(empty_rows))

Empty columns: []
Empty rows: []


In [58]:
import seaborn as sns

import matplotlib.pyplot as plt

features = ['capital-gain', 'capital-loss', 'hours-per-week']

plt.figure(figsize=(18, 5))
for i, feature in enumerate(features, 1):
    plt.subplot(1, 3, i)
    sns.boxplot(data=df, x='target', y=feature)
    plt.title(f'{feature} by Income')
plt.tight_layout()
plt.show()

C:\Users\jojot\AppData\Local\Temp\ipykernel_9484\1319162268.py:13: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


checking how skewed and outliers of capital gain. capital lossnd hours per week by income

In [59]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
sns.histplot(df['capital-gain'], bins=50, kde=True, color='purple')
plt.title('Capital Gain Distribution')
plt.xlabel('Capital Gain')
plt.ylabel('Count')
plt.show()


C:\Users\jojot\AppData\Local\Temp\ipykernel_9484\668136118.py:9: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


In [60]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
sns.histplot(df['capital-loss'], bins=50, kde=True, color='purple')
plt.title('Capital loss Distribution')
plt.xlabel('Capital loss')
plt.ylabel('Count')
plt.show()


C:\Users\jojot\AppData\Local\Temp\ipykernel_9484\1290496057.py:9: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


In [61]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
sns.histplot(df['hours-per-week'], bins=50, kde=True, color='purple')
plt.title('Hours-Per-week Distribution')
plt.xlabel('Hours-Per-week')
plt.ylabel('Count')
plt.show()


C:\Users\jojot\AppData\Local\Temp\ipykernel_9484\1195309053.py:9: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


Removing Outliers

In [62]:
cap_gain_threshold = df['capital-gain'].quantile(0.995)
df = df[df['capital-gain'] <= cap_gain_threshold]

cap_gain_cap = df['capital-gain'].quantile(0.99)
df['capital-gain'] = df['capital-gain'].clip(upper=cap_gain_cap)

cap_loss_threshold = df['capital-loss'].quantile(0.995)
df = df[df['capital-loss'] <= cap_loss_threshold]

cap_loss_cap = df['capital-loss'].quantile(0.99)
df['capital-loss'] = df['capital-loss'].clip(upper=cap_loss_cap)

hours_threshold = df['hours-per-week'].quantile(0.995)
df = df[df['hours-per-week'] <= hours_threshold]

hours_cap = df['hours-per-week'].quantile(0.99)
df['hours-per-week'] = df['hours-per-week'].clip(upper=hours_cap)

Log transformation is used for capital-gain and capital-loss to reduce skewness, handle extreme outliers, and make distributions more normal-like, improving model performance and stability, especially for linear models.


In [63]:
import numpy as np

df['capital-gain'] = df['capital-gain'].apply(lambda x: np.log1p(x))
df['capital-loss'] = df['capital-loss'].apply(lambda x: np.log1p(x))


scaling age, education-num, and hours-per-week because they have different value ranges. Scaling ensures each feature contributes equally, prevents bias toward larger numbers, and improves model performance especially for algorithms sensitive to feature magnitude like logistic regression or SVM.


Scale the variables that need to be scaled to see if scaling or scaling should be used to train the data set. See which which metrics to use

In [64]:
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score, 
    roc_auc_score, average_precision_score, classification_report,
    confusion_matrix, balanced_accuracy_score
)
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
import numpy as np

X_train_combined_scaled = X_train_combined.copy()
X_test_combined_scaled = X_test_combined.copy()

cols_to_scale = ['age', 'hours-per-week']

col_indices = [df.columns.get_loc(col) for col in cols_to_scale]

scaler = StandardScaler()
X_train_combined_scaled[:, col_indices] = scaler.fit_transform(X_train_combined[:, col_indices])
X_test_combined_scaled[:, col_indices] = scaler.transform(X_test_combined[:, col_indices])

def evaluate_imbalanced_model(y_true, y_pred, y_pred_proba=None, pos_label=' >50K'):
    print("CLASSIFICATION METRICS")
    
    accuracy = accuracy_score(y_true, y_pred)
    balanced_acc = balanced_accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, pos_label=pos_label)
    recall = recall_score(y_true, y_pred, pos_label=pos_label)
    f1 = f1_score(y_true, y_pred, pos_label=pos_label)
    
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Balanced Accuracy: {balanced_acc:.4f}")
    print(f"Precision (>50K): {precision:.4f}")
    print(f"Recall (>50K): {recall:.4f}")
    print(f"F1 Score (>50K): {f1:.4f}")
    
    if y_pred_proba is not None:
        y_true_binary = np.array(y_true).ravel() == pos_label
        roc_auc = roc_auc_score(y_true_binary, y_pred_proba)
        print(f"ROC AUC: {roc_auc:.4f}")
        
        avg_precision = average_precision_score(y_true_binary, y_pred_proba)
        print(f"Average Precision (PR AUC): {avg_precision:.4f}")
    else:
        roc_auc = None
        avg_precision = None
    
    cm = confusion_matrix(y_true, y_pred)
    print(f"\nConfusion Matrix:")
    print(f"True Negatives (<=50K): {cm[0,0]}")
    print(f"False Positives (<=50K predicted as >50K): {cm[0,1]}")
    print(f"False Negatives (>50K predicted as <=50K): {cm[1,0]}")
    print(f"True Positives (>50K): {cm[1,1]}")
    
    print(f"\nDETAILED CLASSIFICATION REPORT")
    print(classification_report(y_true, y_pred))
    
    return {
        'accuracy': accuracy,
        'balanced_accuracy': balanced_acc,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'roc_auc': roc_auc,
        'avg_precision': avg_precision
    }

print("LOGISTIC REGRESSION (UNSCALED)")
lr_unscaled = LogisticRegression(max_iter=1000)
lr_unscaled.fit(X_train_combined, y_train_combined)
y_pred_lr_unscaled = lr_unscaled.predict(X_test_combined)
y_pred_proba_lr_unscaled = lr_unscaled.predict_proba(X_test_combined)[:, 1]
evaluate_imbalanced_model(y_test_combined, y_pred_lr_unscaled, y_pred_proba_lr_unscaled)

print("LOGISTIC REGRESSION (SCALED)")
lr_scaled = LogisticRegression(max_iter=1000)
lr_scaled.fit(X_train_combined_scaled, y_train_combined)
y_pred_lr_scaled = lr_scaled.predict(X_test_combined_scaled)
y_pred_proba_lr_scaled = lr_scaled.predict_proba(X_test_combined_scaled)[:, 1]
evaluate_imbalanced_model(y_test_combined, y_pred_lr_scaled, y_pred_proba_lr_scaled)

print("K-NEAREST NEIGHBORS (UNSCALED)")
knn_unscaled = KNeighborsClassifier(n_neighbors=5)
knn_unscaled.fit(X_train_combined, y_train_combined)
y_pred_knn_unscaled = knn_unscaled.predict(X_test_combined)
y_pred_proba_knn_unscaled = knn_unscaled.predict_proba(X_test_combined)[:, 1]
evaluate_imbalanced_model(y_test_combined, y_pred_knn_unscaled, y_pred_proba_knn_unscaled)

print("K-NEAREST NEIGHBORS (SCALED)")
knn_scaled = KNeighborsClassifier(n_neighbors=5)
knn_scaled.fit(X_train_combined_scaled, y_train_combined)
y_pred_knn_scaled = knn_scaled.predict(X_test_combined_scaled)
y_pred_proba_knn_scaled = knn_scaled.predict_proba(X_test_combined_scaled)[:, 1]
evaluate_imbalanced_model(y_test_combined, y_pred_knn_scaled, y_pred_proba_knn_scaled)

print("SUPPORT VECTOR MACHINE (UNSCALED)")
svm_unscaled = SVC(probability=True)
svm_unscaled.fit(X_train_combined, y_train_combined)
y_pred_svm_unscaled = svm_unscaled.predict(X_test_combined)
y_pred_proba_svm_unscaled = svm_unscaled.predict_proba(X_test_combined)[:, 1]
evaluate_imbalanced_model(y_test_combined, y_pred_svm_unscaled, y_pred_proba_svm_unscaled)

print("SUPPORT VECTOR MACHINE (SCALED)")
svm_scaled = SVC(probability=True)
svm_scaled.fit(X_train_combined_scaled, y_train_combined)
y_pred_svm_scaled = svm_scaled.predict(X_test_combined_scaled)
y_pred_proba_svm_scaled = svm_scaled.predict_proba(X_test_combined_scaled)[:, 1]
evaluate_imbalanced_model(y_test_combined, y_pred_svm_scaled, y_pred_proba_svm_scaled)

LOGISTIC REGRESSION (UNSCALED)


C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConver

CLASSIFICATION METRICS
Accuracy: 0.8471
Balanced Accuracy: 0.7631
Precision (>50K): 0.7233
Recall (>50K): 0.5999
F1 Score (>50K): 0.6558
ROC AUC: 0.8996
Average Precision (PR AUC): 0.7578

Confusion Matrix:
True Negatives (<=50K): 4568
False Positives (<=50K predicted as >50K): 363
False Negatives (>50K predicted as <=50K): 633
True Positives (>50K): 949

DETAILED CLASSIFICATION REPORT
              precision    recall  f1-score   support

       <=50K       0.88      0.93      0.90      4931
        >50K       0.72      0.60      0.66      1582

    accuracy                           0.85      6513
   macro avg       0.80      0.76      0.78      6513
weighted avg       0.84      0.85      0.84      6513

LOGISTIC REGRESSION (SCALED)


C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


CLASSIFICATION METRICS
Accuracy: 0.8477
Balanced Accuracy: 0.7612
Precision (>50K): 0.7294
Recall (>50K): 0.5929
F1 Score (>50K): 0.6541
ROC AUC: 0.9006
Average Precision (PR AUC): 0.7570

Confusion Matrix:
True Negatives (<=50K): 4583
False Positives (<=50K predicted as >50K): 348
False Negatives (>50K predicted as <=50K): 644
True Positives (>50K): 938

DETAILED CLASSIFICATION REPORT
              precision    recall  f1-score   support

       <=50K       0.88      0.93      0.90      4931
        >50K       0.73      0.59      0.65      1582

    accuracy                           0.85      6513
   macro avg       0.80      0.76      0.78      6513
weighted avg       0.84      0.85      0.84      6513

K-NEAREST NEIGHBORS (UNSCALED)
CLASSIFICATION METRICS
Accuracy: 0.8400
Balanced Accuracy: 0.7671
Precision (>50K): 0.6878
Recall (>50K): 0.6252
F1 Score (>50K): 0.6550
ROC AUC: 0.8690
Average Precision (PR AUC): 0.7003

Confusion Matrix:
True Negatives (<=50K): 4482
False Positives (

C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


CLASSIFICATION METRICS
Accuracy: 0.8555
Balanced Accuracy: 0.7889
Precision (>50K): 0.7218
Recall (>50K): 0.6593
F1 Score (>50K): 0.6891
ROC AUC: 0.8837
Average Precision (PR AUC): 0.7241

Confusion Matrix:
True Negatives (<=50K): 4529
False Positives (<=50K predicted as >50K): 402
False Negatives (>50K predicted as <=50K): 539
True Positives (>50K): 1043

DETAILED CLASSIFICATION REPORT
              precision    recall  f1-score   support

       <=50K       0.89      0.92      0.91      4931
        >50K       0.72      0.66      0.69      1582

    accuracy                           0.86      6513
   macro avg       0.81      0.79      0.80      6513
weighted avg       0.85      0.86      0.85      6513

SUPPORT VECTOR MACHINE (UNSCALED)


C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


CLASSIFICATION METRICS
Accuracy: 0.8024
Balanced Accuracy: 0.6241
Precision (>50K): 0.7530
Recall (>50K): 0.2775
F1 Score (>50K): 0.4055
ROC AUC: 0.8208
Average Precision (PR AUC): 0.6292

Confusion Matrix:
True Negatives (<=50K): 4787
False Positives (<=50K predicted as >50K): 144
False Negatives (>50K predicted as <=50K): 1143
True Positives (>50K): 439

DETAILED CLASSIFICATION REPORT
              precision    recall  f1-score   support

       <=50K       0.81      0.97      0.88      4931
        >50K       0.75      0.28      0.41      1582

    accuracy                           0.80      6513
   macro avg       0.78      0.62      0.64      6513
weighted avg       0.79      0.80      0.77      6513

SUPPORT VECTOR MACHINE (SCALED)


C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


CLASSIFICATION METRICS
Accuracy: 0.8024
Balanced Accuracy: 0.6241
Precision (>50K): 0.7530
Recall (>50K): 0.2775
F1 Score (>50K): 0.4055
ROC AUC: 0.8708
Average Precision (PR AUC): 0.6871

Confusion Matrix:
True Negatives (<=50K): 4787
False Positives (<=50K predicted as >50K): 144
False Negatives (>50K predicted as <=50K): 1143
True Positives (>50K): 439

DETAILED CLASSIFICATION REPORT
              precision    recall  f1-score   support

       <=50K       0.81      0.97      0.88      4931
        >50K       0.75      0.28      0.41      1582

    accuracy                           0.80      6513
   macro avg       0.78      0.62      0.64      6513
weighted avg       0.79      0.80      0.77      6513



{'accuracy': 0.8023952095808383,
 'balanced_accuracy': 0.6241469190120759,
 'precision': 0.7530017152658662,
 'recall': 0.2774968394437421,
 'f1': 0.40554272517321016,
 'roc_auc': 0.8707552338580887,
 'avg_precision': 0.6870830400690073}

Justification for Using Scaled Data

Better Model Results
- K-Nearest Neighbors (KNN) accuracy improved from 0.8400 to 0.8555, and F1-score from 0.6550 to 0.6891 after scaling.
- Logistic Regression accuracy improved from 0.8471 to 0.8477, and ROC AUC increased from 0.8996 to 0.9006 after scaling.
- Support Vector Machine (SVM) ROC AUC improved significantly from 0.8208 to 0.8708, and Average Precision (PR AUC) from 0.6292 to 0.6871 after scaling, although accuracy and F1-score remained unchanged.

Better Convergence and Stability
- Scaling helps algorithms like Logistic Regression and SVM converge more reliably and faster by putting features on t he same scale.

Distance-Based Algorithms Depend on Scale
- Models like K-Nearest Neighbors arehighly sensitive to feature scale because they rely on distance metrics. Scaling ensures that no single feature dominates simply because of its magnitude.

Consistent Feature Importance
- Scaling maintains relative importance of features without bias from differing units or ranges, improving model interpretability.

I decided to use ROC AUC bacause it does not only measure how right the model is but how well the model ranks positive examples higher than the negative ones. ROC AUC evaluates probability ranking and not the final classification threshold. unlike accuracy ROC AUC is not biased by imbalances classes and in my dataset case <=50k takes up more than 3/4 of the target data. 

In [65]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

param_grid_knn = {
    'n_neighbors': [3, 5, 7, 9, 11],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
}

knn = KNeighborsClassifier()
grid_knn = GridSearchCV(knn, param_grid_knn, scoring='f1', cv=5, verbose=1, n_jobs=-1)
grid_knn.fit(X_train_combined_scaled, y_train_combined.ravel())  

print("Best KNN parameters:", grid_knn.best_params_)
print("Best KNN F1 score:", grid_knn.best_score_)


Fitting 5 folds for each of 20 candidates, totalling 100 fits
Best KNN parameters: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'uniform'}
Best KNN F1 score: nan


C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan]
  warnings.warn(


In [66]:
from sklearn.linear_model import LogisticRegression

param_grid_lr = {
    'C': [0.01, 0.1, 1, 10],
    'penalty': ['l2'],
    'solver': ['lbfgs', 'saga'],
    'max_iter': [1000, 2000]
}

lr = LogisticRegression()
grid_lr = GridSearchCV(lr, param_grid_lr, scoring='f1', cv=5, verbose=1, n_jobs=-1)
grid_lr.fit(X_train_combined_scaled, y_train_combined.ravel())

print("Best Logistic Regression parameters:", grid_lr.best_params_)
print("Best Logistic Regression F1 score:", grid_lr.best_score_)


Fitting 5 folds for each of 16 candidates, totalling 80 fits


C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
  warnings.warn(


Best Logistic Regression parameters: {'C': 0.01, 'max_iter': 1000, 'penalty': 'l2', 'solver': 'lbfgs'}
Best Logistic Regression F1 score: nan


C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [67]:
best_knn = grid_knn.best_estimator_  
best_lr = grid_lr.best_estimator_   


In [68]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

y_pred_knn = best_knn.predict(X_test_combined_scaled)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_knn))

print("Classification Report:")
print(classification_report(y_test, y_pred_knn))

print("ROC AUC Score:", roc_auc_score(y_test, best_knn.predict_proba(X_test_combined_scaled)[:, 1]))


Confusion Matrix:
[[4497  434]
 [ 514 1068]]
Classification Report:
              precision    recall  f1-score   support

       <=50K       0.90      0.91      0.90      4931
        >50K       0.71      0.68      0.69      1582

    accuracy                           0.85      6513
   macro avg       0.80      0.79      0.80      6513
weighted avg       0.85      0.85      0.85      6513

ROC AUC Score: 0.8594561971643574


In [69]:
import pandas as pd

# Collect results for each model and scaling combination
results_table = pd.DataFrame({
    'Model': [
        'Logistic Regression (Unscaled)',
        'Logistic Regression (Scaled)',
        'KNN (Unscaled)',
        'KNN (Scaled)',
        'SVM (Unscaled)',
        'SVM (Scaled)'
    ],
    'Accuracy': [
        lr_unscaled.score(X_test_combined, y_test_combined),
        lr_scaled.score(X_test_combined_scaled, y_test_combined),
        knn_unscaled.score(X_test_combined, y_test_combined),
        knn_scaled.score(X_test_combined_scaled, y_test_combined),
        svm_unscaled.score(X_test_combined, y_test_combined),
        svm_scaled.score(X_test_combined_scaled, y_test_combined)
    ],
    'F1 Score': [
        f1_score(y_test_combined, y_pred_lr_unscaled, pos_label=' >50K'),
        f1_score(y_test_combined, y_pred_lr_scaled, pos_label=' >50K'),
        f1_score(y_test_combined, y_pred_knn_unscaled, pos_label=' >50K'),
        f1_score(y_test_combined, y_pred_knn_scaled, pos_label=' >50K'),
        f1_score(y_test_combined, y_pred_svm_unscaled, pos_label=' >50K'),
        f1_score(y_test_combined, y_pred_svm_scaled, pos_label=' >50K')
    ],
    'ROC AUC': [
        roc_auc_score(y_test_combined, y_pred_proba_lr_unscaled),
        roc_auc_score(y_test_combined, y_pred_proba_lr_scaled),
        roc_auc_score(y_test_combined, y_pred_proba_knn_unscaled),
        roc_auc_score(y_test_combined, y_pred_proba_knn_scaled),
        roc_auc_score(y_test_combined, y_pred_proba_svm_unscaled),
        roc_auc_score(y_test_combined, y_pred_proba_svm_scaled)
    ]
})

print(results_table)

                            Model  Accuracy  F1 Score   ROC AUC
0  Logistic Regression (Unscaled)  0.847075  0.655840  0.899622
1    Logistic Regression (Scaled)  0.847689  0.654114  0.900625
2                  KNN (Unscaled)  0.840012  0.654967  0.869043
3                    KNN (Scaled)  0.855520  0.689131  0.883714
4                  SVM (Unscaled)  0.802395  0.405543  0.820766
5                    SVM (Scaled)  0.802395  0.405543  0.870755


In [70]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

feature_names = [col for col in df.columns if col != 'target']

feature_importance = pd.DataFrame({
    'Feature': feature_names,
    'Importance': lr_scaled.coef_[0]
}).sort_values(by='Importance', key=np.abs, ascending=False)

print(feature_importance)


                               Feature  Importance
31             relationship_ Own-child   -1.768581
89                education_ Doctorate    1.569483
93              education_ Prof-school    1.463078
84                  education_ 7th-8th   -1.457472
33                  relationship_ Wife    1.300568
..                                 ...         ...
53  native-country_ Holand-Netherlands   -0.002883
72            native-country_ Scotland    0.002522
75            native-country_ Thailand   -0.001574
2                         capital-loss    0.000643
1                         capital-gain    0.000311

[96 rows x 2 columns]


In [ ]:
low_importance_features = feature_importance.loc[feature_importance['Importance'].abs() < 0.01, 'Feature'].tolist()
print("Features to drop:", low_importance_features)

Features to drop: ['native-country_ Cuba', 'native-country_ Holand-Netherlands', 'native-country_ Scotland', 'native-country_ Thailand', 'capital-loss', 'capital-gain']


In [82]:
df1 = df1.drop(columns=low_importance_features)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score


lr_final = LogisticRegression(max_iter=1000)
lr_final.fit(X_train_combined_scaled, y_train_combined)
y_pred_lr_final = lr_final.predict(X_test_combined_scaled)


print("Classification Report:")
print(classification_report(y_test_combined, y_pred_lr_final))

y_pred_proba_lr_final = lr_final.predict_proba(X_test_combined_scaled)[:, 1]
print("ROC AUC Score:", roc_auc_score(y_test_combined, y_pred_proba_lr_final))

C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Classification Report:
              precision    recall  f1-score   support

       <=50K       0.88      0.93      0.90      4931
        >50K       0.73      0.59      0.65      1582

    accuracy                           0.85      6513
   macro avg       0.80      0.76      0.78      6513
weighted avg       0.84      0.85      0.84      6513

ROC AUC Score: 0.9006245736037212


C:\Users\jojot\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [84]:
from sklearn.metrics import classification_report, roc_auc_score

y_pred_old = lr_scaled.predict(X_test_combined_scaled)
y_pred_proba_old = lr_scaled.predict_proba(X_test_combined_scaled)[:, 1]

y_pred_new = lr_final.predict(X_test_combined_scaled)
y_pred_proba_new = lr_final.predict_proba(X_test_combined_scaled)[:, 1]

print("OLD MODEL (Before dropping columns)")
print(classification_report(y_test_combined, y_pred_old))
print("ROC AUC:", roc_auc_score(y_test_combined, y_pred_proba_old))

print("\nNEW MODEL (After dropping columns)")
print(classification_report(y_test_combined, y_pred_new))
print("ROC AUC:", roc_auc_score(y_test_combined, y_pred_proba_new))

OLD MODEL (Before dropping columns)
              precision    recall  f1-score   support

       <=50K       0.88      0.93      0.90      4931
        >50K       0.73      0.59      0.65      1582

    accuracy                           0.85      6513
   macro avg       0.80      0.76      0.78      6513
weighted avg       0.84      0.85      0.84      6513

ROC AUC: 0.9006245736037212

NEW MODEL (After dropping columns)
              precision    recall  f1-score   support

       <=50K       0.88      0.93      0.90      4931
        >50K       0.73      0.59      0.65      1582

    accuracy                           0.85      6513
   macro avg       0.80      0.76      0.78      6513
weighted avg       0.84      0.85      0.84      6513

ROC AUC: 0.9006245736037212


old model ROC AUC: 0.9006245736037212, new model ROC AUC: 0.9006245736037212 due to no differences made, before and after dropping less important features, I will not drop them.

In [71]:
# import pandas as pd

# sample_input = pd.DataFrame([{
#     'age': 37,
#     'education-num': 13,
#     'capital-gain': 0,
#     'capital-loss': 0,
#     'hours-per-week': 45,
#     'workclass': 'Private',
#     'marital-status': 'Married-civ-spouse',
#     'occupation': 'Exec-managerial',
#     'relationship': 'Husband',
#     'race': 'White',
#     'sex': 'Male',
#     'native-country': 'United-States'
# }])

# sample_input_encoded = pd.get_dummies(sample_input)
# for col in df.columns:
#     if col not in sample_input_encoded.columns and col != 'target':
#         sample_input_encoded[col] = False if df[col].dtype == bool else 0

# sample_input_encoded = sample_input_encoded[[col for col in df.columns if col != 'target']]

# import numpy as np
# sample_input_encoded['capital-gain'] = np.log1p(sample_input_encoded['capital-gain'])
# sample_input_encoded['capital-loss'] = np.log1p(sample_input_encoded['capital-loss'])

# cols_to_scale = ['age', 'education-num', 'hours-per-week']
# col_indices = [sample_input_encoded.columns.get_loc(col) for col in cols_to_scale]
# sample_input_np = sample_input_encoded.to_numpy().astype(float)

# sample_input_np[:, col_indices] = scaler.transform(sample_input_np[:, col_indices])

# prediction = best_knn.predict(sample_input_np)
# print("Predicted Income:", prediction[0])


In [72]:
# sample_input_high_income = pd.DataFrame([{
#     'age': 45,
#     'education-num': 16, 
#     'capital-gain': 10000, 
#     'capital-loss': 0,
#     'hours-per-week': 70, 
#     'workclass': 'Private',
#     'marital-status': 'Married-civ-spouse',
#     'occupation': 'Exec-managerial',
#     'relationship': 'Husband',
#     'race': 'White',
#     'sex': 'Male',
#     'native-country': 'United-States'
# }])

# sample_input_high_income_encoded = pd.get_dummies(sample_input_high_income)
# for col in df.columns:
#     if col not in sample_input_high_income_encoded.columns and col != 'target':
#         sample_input_high_income_encoded[col] = False if df[col].dtype == bool else 0
# sample_input_high_income_encoded = sample_input_high_income_encoded[[col for col in df.columns if col != 'target']]

# sample_input_high_income_encoded['capital-gain'] = np.log1p(sample_input_high_income_encoded['capital-gain'])
# sample_input_high_income_encoded['capital-loss'] = np.log1p(sample_input_high_income_encoded['capital-loss'])

# sample_input_high_income_np = sample_input_high_income_encoded.to_numpy().astype(float)
# sample_input_high_income_np[:, col_indices] = scaler.transform(sample_input_high_income_np[:, col_indices])

# prediction_high_income = best_knn.predict(sample_input_high_income_np)
# print("Predicted Income:", prediction_high_income[0])

In [85]:
import joblib
joblib.dump(lr_scaled, 'model.pkl')

['model.pkl']

In [74]:
# from sklearn.pipeline import Pipeline
# from sklearn.preprocessing import StandardScaler
# from sklearn.linear_model import LogisticRegression

In [75]:
# pipeline = Pipeline([
#     ('scaler', StandardScaler()), 
#     ('classifier', LogisticRegression())  
# ])

In [76]:
# import joblib
# joblib.dump(scaler, 'scaler.pkl')  


In [77]:
# roc_auc = roc_auc_score(y_test_combined, y_pred_proba_lr_scaled)

In [78]:
# joblib.dump({
#     'model': lr_scaled,
#     'roc_auc': roc_auc,
#     'expected_columns': list(df.drop('target', axis=1).columns)
# }, 'logistic_scaled_with_auc.joblib')


In [79]:
# from sklearn.compose import ColumnTransformer
# from sklearn.pipeline import Pipeline
# from sklearn.preprocessing import OneHotEncoder, StandardScaler
# from sklearn.linear_model import LogisticRegression
# import joblib

# # Indices of columns to scale
# cols_to_scale = ['age', 'education-num', 'hours-per-week']
# col_indices = [df.columns.get_loc(col) for col in cols_to_scale]

# # Define categorical columns as all boolean columns except numeric and target
# categorical_cols = [col for col in df.columns if df[col].dtype == bool and col not in cols_to_scale and col != 'target']
# numeric_cols = cols_to_scale

# preprocessor = ColumnTransformer([
#     ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols),
#     ('num', StandardScaler(), numeric_cols)
# ])

# pipeline = Pipeline([
#     ('preprocessor', preprocessor),
#     ('classifier', lr_scaled)
# ])

# # Use pandas DataFrame for pipeline input so column names work
# X_train_df = df.drop('target', axis=1).iloc[X_train_combined_scaled.shape[0]*-1:]
# X_test_df = df.drop('target', axis=1).iloc[-X_test_combined_scaled.shape[0]:]

# pipeline.fit(X_train_df, y_train_combined)
# joblib.dump(pipeline, 'salary_pipeline.joblib')

# y_pred_pipeline = pipeline.predict(X_test_df)